import {test} from 'node:test';
import assert from 'node:assert/strict';
import {createStore} from '../server/store.js';
import {loadScenario} from '../server/content.js';
import {workshopScenario} from '../server/scenario-config.js';
import {readEncounter,mutateEncounter} from '../server/itsm-encounter.js';
import {readITSM,mutateITSM} from '../server/itsm-engine.js';
import {animalRoles,animalView} from '../server/animal-encounter.js';
async function fixture(t){const scenario=loadScenario(),store=createStore(':memory:',scenario,{password:'test-only-password'});t.after(()=>store.db.close());const trainer=store.one('SELECT * FROM users WHERE trainer=1'),wid=store.one('SELECT id FROM workshops').id;await workshopScenario(store,scenario,wid);const users={};for(let n=1;n<=8;n++){const role='R'+n;users[role]={id:'animal-'+n,name:role,trainer:0};store.run('INSERT INTO users VALUES(?,?,?,?,0)',users[role].id,users[role].id,role,'not-login');store.run('INSERT INTO memberships VALUES(?,?,?)',wid,users[role].id,role);}for(const eventId of ['E02','E09','E10'])await mutateITSM({store,scenario,wid,user:trainer,input:{action:'release',eventId},revision:1});let now=1000000;const read=()=>readEncounter(store,wid,'R2',false,now);async function act(role,operation,extra={}){const state=await read();return mutateEncounter({store,wid,user:role==='trainer'?trainer:users[role],role,animal:operation.startsWith('animal_'),input:{operation,requestId:crypto.randomUUID(),runtimeRevision:state.revision,...extra},now});}return{store,scenario,wid,trainer,users,read,act,advance:n=>now+=n*1000};}
async function prepare(f,type){for(const role of ['R2','R3','R4','R7','R8'])await f.act(role,'animal_share');await f.act('R5','animal_inspect');await f.act('R4','animal_plan',{option:type,note:'Elif ve PA sessiz alan testi; başarısızsa alan kapalı kalacak.'});await f.act('R1','animal_fund');await f.act('R6','animal_approve');await f.act('trainer','pace',{option:'1'});}
for(const type of ['partial','delay','quiet'])test(`animal service ${type}: eight-role workflow, humane acceptance and exact event outcomes`,async t=>{const f=await fixture(t);await prepare(f,type);if(type==='quiet'){await assert.rejects(f.act('R4','animal_execute'),{status:409});await f.act('R7','animal_keeper');f.advance(60);}await f.act('R4','animal_execute');await assert.rejects(f.act('R2','animal_accept',{note:'Henüz saha kabulü yok; bu işlem engellenmeli.'}),{status:409});let s=await f.read();assert.equal(s.credits,type==='quiet'?80:100);assert.equal(s.animal.habitat,'quiet_closed');f.advance(type==='partial'?30:type==='delay'?180:90);await f.act('R3','animal_validate',{option:'pass'});await f.act('R2','animal_accept',{note:'Nermin Hoca yeni kapsamı ve bekleme süresini kabul etti.'});s=await f.read();assert.equal(s.animal.accepted,true);assert.equal(s.animal.habitat,type==='partial'?'quiet_closed':'quiet_open');const view=animalView(s,'R2',false,true,['E02','E09','E10']);assert.equal(view.privateFact.includes('Sponsor'),true);assert.equal(view.trainerFacts,undefined);for(const eid of ['E02','E09','E10']){const record=f.store.one('SELECT * FROM simulation_records WHERE workshop_id=? AND event_id=?',f.wid,eid);await mutateITSM({store:f.store,scenario:f.scenario,wid:f.wid,user:f.trainer,input:{action:'ack',recordId:record.id}});const event=f.scenario.events.find(e=>e.id===eid);const wrong=event.choices.find(c=>c.resolve&&c.animalOutcome!==type);await assert.rejects(mutateITSM({store:f.store,scenario:f.scenario,wid:f.wid,user:f.trainer,input:{action:'evaluate',recordId:record.id,choiceId:wrong.id,note:'Yanlış sonuç gerçek planla eşleşmediği için reddedilmeli.'}}),{status:409});await mutateITSM({store:f.store,scenario:f.scenario,wid:f.wid,user:f.trainer,input:{action:'evaluate',recordId:record.id,choiceId:event.choices.find(c=>c.animalOutcome===type).id,note:'Gerçek plan, saha testi ve ziyaretçi kabulü doğrulandı.'}});}assert.equal(f.store.all('SELECT * FROM simulation_records WHERE workshop_id=? AND resolved_at IS NOT NULL',f.wid).length,3);});
test('animal role enforcement and private facts are server-derived; closed gates reject early approval',async t=>{const f=await fixture(t);for(const role of Object.keys(f.users))for(const op of ['animal_share','animal_inspect','animal_plan','animal_fund','animal_approve','animal_keeper','animal_execute','animal_validate','animal_accept'])if(!animalRoles[role].includes(op))await assert.rejects(f.act(role,op),{status:403});await assert.rejects(f.act('R6','animal_approve'),{status:409});const view=await readITSM(f.store,f.scenario,f.wid,false,'R2');assert.equal(view.encounter.animal,undefined);assert.equal(view.animals.shared.R3,undefined);assert.equal(view.animals.trainerFacts,undefined);assert.match(view.animals.privateFact,/Sponsor/);});
test('animal work shares technician contention, preserves reserve and failed test requires new approval',async t=>{const f=await fixture(t);await prepare(f,'quiet');await f.act('R7','animal_keeper');f.advance(60);const row=f.store.one('SELECT state FROM simulation_runtime WHERE workshop_id=?',f.wid),runtime=JSON.parse(row.state);runtime.jobs.push({type:'support',technicians:2,until:200,done:false});f.store.run('UPDATE simulation_runtime SET state=? WHERE workshop_id=?',JSON.stringify(runtime),f.wid);await assert.rejects(f.act('R4','animal_execute'),{status:409});f.advance(140);await f.act('R4','animal_execute');f.advance(90);await f.act('R3','animal_validate',{option:'fail'});let s=await f.read();assert.equal(s.animal.habitat,'quiet_closed');assert.equal(s.animal.approved,false);assert.equal(s.credits,80);await assert.rejects(f.act('R3','animal_validate',{option:'pass'}),{status:409});await f.act('R4','animal_plan',{option:'partial',note:'Gözlem kapalı, alternatif rota güvenli saha testiyle açılacak.'});await f.act('R1','animal_fund');await f.act('R6','animal_approve');await f.act('R4','animal_execute');f.advance(30);await f.act('R3','animal_validate',{option:'pass'});assert.equal((await f.read()).animal.habitat,'quiet_closed');});
test('legacy scenario remains unchanged and cannot silently acquire animal outcomes',async t=>{const f=await fixture(t);const old=structuredClone(f.scenario);delete old.animalModel;const view=await readITSM(f.store,old,f.wid,true);assert.equal(view.animals.enabled,false);await assert.rejects(mutateITSM({store:f.store,scenario:old,wid:f.wid,user:f.trainer,input:{action:'animal',operation:'animal_share',option:'R3',requestId:crypto.randomUUID(),runtimeRevision:0}}),{status:409});assert.equal(view.metrics.score,0);});
test('animal UI controls and escaped history reflect actual safe partial state',async t=>{const {animalPanel,animalCards}=await import('../public/animal-encounter.js');const f=await fixture(t);await prepare(f,'partial');await f.act('R4','animal_execute');f.advance(30);await f.act('R3','animal_validate',{option:'pass'});await f.act('R2','animal_accept',{note:'Alternatif rota kabul edildi; Mümtaz gözlemi kapalı kalıyor.'});const itsm=await readITSM(f.store,f.scenario,f.wid,false,'R2');const s={user:f.users.R2,roleId:'R2',scenario:f.scenario,itsm};const html=animalPanel(s);assert.match(html,/data-habitat="quiet_closed"/);assert.doesNotMatch(html,/data-op="animal_execute"/);assert.match(html,/Güvenli kısmi açılış/);assert.match(animalCards(s),/MV-A-001/);});
test('free humane fallback remains possible after technical recovery spent the reserve',async t=>{const f=await fixture(t);await prepare(f,'partial');const row=f.store.one('SELECT state FROM simulation_runtime WHERE workshop_id=?',f.wid),state=JSON.parse(row.state);state.credits=5;state.validated=true;state.water='resilient';state.animal.funded=false;state.animal.approved=false;f.store.run('UPDATE simulation_runtime SET state=? WHERE workshop_id=?',JSON.stringify(state),f.wid);await f.act('R1','animal_fund');await f.act('R6','animal_approve');await f.act('R4','animal_execute');f.advance(30);await f.act('R3','animal_validate',{option:'pass'});await f.act('R2','animal_accept',{note:'Ücretsiz güvenli alternatif rota ziyaretçi tarafından kabul edildi.'});assert.equal((await f.read()).credits,5);assert.equal((await f.read()).animal.accepted,true);});
