import {test} from 'node:test';
import assert from 'node:assert/strict';
import {createStore} from '../server/store.js';
import {loadScenario} from '../server/content.js';
import {mutateITSM,readITSM} from '../server/itsm-engine.js';
import {mutateEncounter,readEncounter,projectEncounter} from '../server/itsm-encounter.js';
import {workshopScenario} from '../server/scenario-config.js';
async function fixture(t){const scenario=loadScenario(),store=createStore(':memory:',scenario,{password:'test-password'});t.after(()=>store.db.close());const trainer=store.one('SELECT * FROM users WHERE trainer=1'),wid=store.one('SELECT id FROM workshops').id;await workshopScenario(store,scenario,wid);const users={};for(let n=1;n<=8;n++){const role=`R${n}`,id=`user-${n}`;store.run('INSERT INTO users VALUES(?,?,?,?,0)',id,id,role,'not-a-login-password');store.run('INSERT INTO memberships VALUES(?,?,?)',wid,id,role);users[role]={id,name:role,trainer:0};}await mutateITSM({store,scenario,wid,user:trainer,input:{action:'release',eventId:'E06'},revision:1});const read=role=>readEncounter(store,wid,role,false,1000000);async function act(role,operation,extra={},at=1000000){const state=await readEncounter(store,wid,role,false,at);return mutateEncounter({store,wid,user:role==='trainer'?trainer:users[role],role:role==='trainer'?null:role,input:{requestId:crypto.randomUUID(),runtimeRevision:state.revision,operation,...extra},now:at});}return{store,scenario,wid,trainer,users,read,act};}
async function prepare(f,type='isolate'){for(const role of ['R2','R3','R4'])await f.act(role,'share');await f.act('R5','inspect');await f.act('R4','plan',{option:type,note:'B1 kesilir, gerçek akış ölçülür; başarısızlıkta güvenli kapalı rota uygulanır.'});await f.act('R1','fund');await f.act('R6','approve');}
test('role-private facts, hidden diagnostics and explicit sharing avoid answer leakage',async t=>{const f=await fixture(t),r2=await f.read('R2');assert.match(r2.privateFact,/40 kişisi/);assert.equal(r2.shared.R4,undefined);assert.equal(r2.trainerFacts,undefined);assert.equal(r2.requests,undefined);const view=await readITSM(f.store,f.scenario,f.wid,false,'R2');assert.ok(!JSON.stringify(view).includes('İki pompa da aynı panoya bağlı'));assert.ok(!view.events[0].message.includes('aynı panoya'));assert.ok(!view.events[0].information.includes('P1 → B1'));assert.notEqual(view.cis.find(c=>c.id==='CI-P2').dependsOn,'CI-B1');await f.act('R4','share');assert.match((await f.read('R2')).shared.R4,/B1/);});
test('all eight roles reject foreign encounter actions and member cannot fake trainer or role',async t=>{const f=await fixture(t);const valid={share:['R2','R3','R4','R5','R7','R8'],inspect:['R4','R5'],plan:['R4'],fund:['R1'],approve:['R6'],execute:['R4'],validate:['R3'],support:['R7'],pace:[]};for(const [operation,allowed] of Object.entries(valid)){for(const role of Object.keys(f.users)){if(!allowed.includes(role))await assert.rejects(f.act(role,operation),{status:403});}}const record=f.store.one('SELECT * FROM simulation_records WHERE workshop_id=?',f.wid);await assert.rejects(mutateITSM({store:f.store,scenario:f.scenario,wid:f.wid,user:f.users.R2,input:{action:'ack',recordId:record.id,role:'R4',trainer:true}}),{status:403});await assert.rejects(mutateITSM({store:f.store,scenario:f.scenario,wid:f.wid,user:f.users.R3,input:{action:'niles',recordId:record.id,url:'https://niles-grc.com/incidents/1'}}),{status:403});});
test('CMDB, business impact, field evidence, funding and approval are hard prerequisites',async t=>{const f=await fixture(t);await assert.rejects(f.act('R4','execute'),{status:409});await assert.rejects(f.act('R5','inspect'),{status:409});await f.act('R4','share');await f.act('R4','inspect');await f.act('R4','plan',{option:'isolate',note:'B1 arızasında akış testi; başarısızsa kapalı alan.'});await assert.rejects(f.act('R6','approve'),{status:409});await f.act('R1','fund');await assert.rejects(f.act('R6','approve'),{status:409});await f.act('R2','share');await f.act('R3','share');await f.act('R6','approve');await f.act('R4','execute');const s=await f.read('R2');assert.equal(s.credits,55);assert.equal(s.available,0);assert.equal(s.network,'up');assert.equal(s.water,'repairing');await assert.rejects(f.act('R3','validate'),{status:409});});
test('resource contention, pause, speed, reconnect and durable field acceptance',async t=>{const f=await fixture(t);await prepare(f);await f.act('R7','support');await assert.rejects(f.act('R4','execute'),{status:409});await f.act('trainer','pace',{option:'3'});let s=await readEncounter(f.store,f.wid,'R4',false,1030000);assert.equal(s.available,2);await f.act('R4','execute',{},1030000);await f.act('trainer','pace',{option:'pause'},1040000);s=await readEncounter(f.store,f.wid,'R4',false,9999999);assert.equal(s.water,'repairing');assert.equal(s.available,0);await f.act('trainer','pace',{option:'6'},1040000);s=await readEncounter(f.store,f.wid,'R4',false,1055000);assert.equal(s.water,'test_pending');assert.equal(s.available,2);await f.act('R3','validate',{},1055000);s=await readEncounter(f.store,f.wid,'R4',false,2055000);assert.equal(s.water,'resilient');assert.equal(s.credits,65);assert.ok(s.history.some(h=>h.message.includes('Saha kabulü')));});
test('cheap restart disrupts dependent network, recurs and allows a new permanent plan',async t=>{const f=await fixture(t);await prepare(f,'restart');await f.act('trainer','pace',{option:'1'});await f.act('R4','execute');let s=await f.read('R2');assert.equal(s.network,'down');assert.equal(s.credits,90);s=await readEncounter(f.store,f.wid,'R2',false,1045000);assert.equal(s.water,'temporary');assert.equal(s.network,'up');s=await readEncounter(f.store,f.wid,'R2',false,1225000);assert.equal(s.water,'degraded');assert.equal(s.plan,null);assert.equal(s.validated,false);await f.act('R4','plan',{option:'isolate',note:'Bağımsız besleme testi ve güvenli geri dönüş koşulu.'},1225000);assert.equal((await readEncounter(f.store,f.wid,'R2',false,1225000)).credits,90);});
test('idempotency replays exactly once; stale concurrent decisions cannot double-spend',async t=>{const f=await fixture(t);await prepare(f);const before=await f.read('R4');const input={requestId:'execute-once-0001',operation:'execute',runtimeRevision:before.revision};const args={store:f.store,wid:f.wid,user:f.users.R4,role:'R4',input,now:1000000};await mutateEncounter(args);await mutateEncounter(args);assert.equal((await f.read('R2')).credits,55);await assert.rejects(mutateEncounter({...args,input:{...input,option:'different'}}),{status:409});await assert.rejects(mutateEncounter({...args,input:{...input,requestId:'execute-stale-0002'}}),{status:409});assert.equal((await f.read('R2')).jobs.length,1);});
test('lazy migration leaves pre-existing scores and SLA untouched; time projection is pure',async t=>{const f=await fixture(t);const record=f.store.one('SELECT * FROM simulation_records WHERE workshop_id=?',f.wid);const s=await f.read('R2');const a=projectEncounter(s,1100000),b=projectEncounter(s,1100000);assert.deepEqual(a,b);assert.equal(s.credits,100);assert.deepEqual(f.store.one('SELECT * FROM simulation_records WHERE id=?',record.id),record);});

test('rendered role controls and resource scenes derive from authorized server state',async t=>{
 const {encounterPanel,authorityPanel}=await import('../public/encounter.js');const f=await fixture(t);await prepare(f);await f.act('R4','execute');const itsm=await readITSM(f.store,f.scenario,f.wid,false,'R2'),s={user:f.users.R2,roleId:'R2',itsm};
 const markup=encounterPanel(s);assert.match(markup,/0 \/ 2/);assert.match(markup,/data-state="repairing"/);assert.doesNotMatch(markup,/data-op="execute"|data-op="approve"|data-op="pace"/);assert.match(authorityPanel(s),/Yapamam/);
 const escaped=encounterPanel({...s,itsm:{...itsm,encounter:{...itsm.encounter,history:[{at:0,actor:'<script>',message:'<img onerror=bad>'}]}}},true);assert.ok(!escaped.includes('<script>'));assert.match(escaped,/&lt;script&gt;/);
});

test('temporary restoration can be replaced before recurrence without a forced second failure',async t=>{
 const f=await fixture(t);await prepare(f,'restart');await f.act('trainer','pace',{option:'1'});await f.act('R4','execute');
 await f.act('R4','plan',{option:'isolate',note:'Geçici hizmet penceresinde bağımsız besleme ve saha kabulü.'},1045000);await f.act('R1','fund',{},1045000);await f.act('R6','approve',{},1045000);await f.act('R4','execute',{},1045000);
 const s=await readEncounter(f.store,f.wid,'R2',false,1165000);assert.equal(s.water,'test_pending');assert.equal(s.credits,45);assert.equal(s.recurrenceAt,null);
});

test('recovery reserve prevents repeated-restart deadlock and discounted funding remains possible',async t=>{
 const f=await fixture(t);await prepare(f,'restart');await f.act('trainer','pace',{option:'1'});let at=1000000;
 for(let n=0;n<6;n++){if(n){await f.act('R4','plan',{option:'restart',note:'Geçici hizmet, ağ kesintisi ve tekrar riski kaydedildi.'},at);await f.act('R1','fund',{},at);await f.act('R6','approve',{},at);}await f.act('R4','execute',{},at);at+=225000;}
 assert.equal((await readEncounter(f.store,f.wid,'R1',false,at)).credits,40);
 await f.act('R4','plan',{option:'restart',note:'Rezervi aşan yedinci deneme sunucuda engellenmeli.'},at);await assert.rejects(f.act('R1','fund',{},at),{status:409});
 await f.act('R7','support',{},at);at+=90000;await f.act('R4','plan',{option:'isolate',note:'Hazırlık indirimiyle bağımsız besleme ve saha kabul testi.'},at);await f.act('R1','fund',{},at);await f.act('R6','approve',{},at);await f.act('R4','execute',{},at);at+=120000;await f.act('R3','validate',{},at);
 const s=await readEncounter(f.store,f.wid,'R1',false,at);assert.equal(s.water,'resilient');assert.equal(s.credits,5);
});

test('legacy accepted change is inherited without inventing resource history or reopening service failure',async t=>{
 const f=await fixture(t);await mutateITSM({store:f.store,scenario:f.scenario,wid:f.wid,user:f.trainer,input:{action:'release',eventId:'E05'},revision:1});await mutateITSM({store:f.store,scenario:f.scenario,wid:f.wid,user:f.trainer,input:{action:'release',eventId:'E07'},revision:1});
 f.store.run("UPDATE simulation_records SET resolved_at=123,status='resolved' WHERE workshop_id=? AND event_id='E07'",f.wid);f.store.run('DELETE FROM simulation_runtime WHERE workshop_id=?',f.wid);
 const s=await f.read('R2');assert.equal(s.legacyAccepted,true);assert.equal(s.legacyAcceptedAt,123);assert.equal(s.water,'resilient');assert.equal(s.active,false);assert.equal(s.jobs.length,0);assert.equal(s.validated,true);assert.match(s.history[0].message,/bilinmiyor/);
 const i=await readITSM(f.store,f.scenario,f.wid,false,'R2');assert.ok(!i.effects.includes('water'));assert.equal(i.cis.find(c=>c.id==='CI-P2').dependsOn,null);assert.equal(i.records.find(r=>r.event_id==='E07').resolved_at,123);await assert.rejects(f.act('R4','plan',{option:'restart',note:'Önceki kabulü yeniden yazmak yetki vermemeli.'}),{status:409});
});

test('completed pump encounter keeps completion guidance after all released records close',async t=>{const f=await fixture(t);await prepare(f);await f.act('trainer','pace',{option:'1'});await f.act('R4','execute');await f.act('R3','validate',{},1120000);f.store.run("UPDATE simulation_records SET status='resolved',resolved_at=123 WHERE workshop_id=?",f.wid);const state=await readEncounter(f.store,f.wid,'R2',false,1120000);assert.equal(state.active,false);assert.equal(state.validated,true);assert.match(state.next,/doğrulandı/);assert.doesNotMatch(state.next,/kartını gönderin/);});
