import {test} from 'node:test';
import assert from 'node:assert/strict';
import {createStore} from '../server/store.js';
import {loadScenario} from '../server/content.js';
import {workshopScenario,validateScenario,saveWorkshopScenario} from '../server/scenario-config.js';
import {mutateITSM,readITSM,slaStatus} from '../server/itsm-engine.js';
import {readEncounter} from '../server/itsm-encounter.js';
import {learningPage,learningForm} from '../public/learning.js';
async function fixture(t,legacy=false){const scenario=loadScenario();if(legacy){delete scenario.learningModel;delete scenario.learningAcceptance;delete scenario.releaseBundles;}const store=createStore(':memory:',scenario,{password:'test-only-password'});t.after(()=>store.db.close());const trainer=store.one('SELECT * FROM users WHERE trainer=1'),wid=store.one('SELECT id FROM workshops').id;await workshopScenario(store,scenario,wid);const users={};for(let n=1;n<=8;n++){const role='R'+n,id='learner-'+n;store.run('INSERT INTO users VALUES(?,?,?,?,0)',id,id,role,'fixture-not-login');store.run('INSERT INTO memberships VALUES(?,?,?)',wid,id,role);users[role]={id,name:role,trainer:0};}const act=(role,input)=>mutateITSM({store,scenario,wid,user:role==='trainer'?trainer:users[role],input,revision:1});const read=role=>readITSM(store,scenario,wid,role==='trainer',role==='trainer'?null:role);const learn=async(role,operation,extra={})=>act(role,{action:'learning',operation,requestId:crypto.randomUUID(),runtimeRevision:(await readEncounter(store,wid,role,false)).revision,...extra});const release=id=>act('trainer',{action:'release',eventId:id});async function note(role,id){await act(role,{action:'note',recordId:wid+'__'+id,note:'Kaydedilmiş saha gözlemi: bağımlılık ve hizmet koşulu kontrollü olarak sınandı.'});return store.all('SELECT * FROM simulation_decisions WHERE workshop_id=? AND event_id=?',wid,id).at(-1).id;}return{store,scenario,trainer,wid,users,act,read,learn,release,note};}
const content={title:'Turnike hizmeti için kontrollü inceleme',scope:'Bilet doğrulama hizmeti etkilenince yalnız verilen oyun koşullarında uygulanır.',procedure:'Kaydı ve bağımlılığı kontrol et; gerçek ziyaretçi geçişiyle hizmeti doğrula.',limits:'Saha teyidi başarısızsa alanı kapalı tut ve yetkili değişiklik rolüne devret.'};
async function draft(f){await f.release('E01');const evidenceId=await f.note('R2','E01');await f.learn('R5','draft',{...content,eventId:'E01',evidenceId});return (await f.read('R5')).learning.articles.at(-1);}
async function publish(f,a){await f.learn('R5','submit',{articleId:a.id});await f.learn('R8','review',{articleId:a.id,option:'approve',note:'Kaynak olay kanıtı, uygulanma sınırı ve geri dönüş koşulu bağımsız incelendi.'});await f.learn('R5','publish',{articleId:a.id});}
test('atomic bundle fairness, duplicate timestamps and ordinary member cannot release',async t=>{const f=await fixture(t);await assert.rejects(f.act('R2',{action:'release',eventId:'E02'}),{status:403});await f.release('E10');let v=await f.read('trainer');assert.equal(v.records.length,3);assert.equal(new Set(v.records.map(r=>r.created_at)).size,1);const r=v.records.find(r=>r.event_id==='E02');assert.equal(r.due_at-r.created_at,18*60000);await f.act('R2',{action:'ack',recordId:r.id});const original=f.store.one('SELECT * FROM simulation_records WHERE id=?',r.id);await Promise.all([f.release('E02'),f.release('E09')]);assert.deepEqual(f.store.one('SELECT * FROM simulation_records WHERE id=?',r.id),original);assert.equal((await f.read('R2')).records.length,3);assert.equal(slaStatus(r,r.due_at).breached,false);assert.equal(slaStatus(r,r.due_at+1).breached,true);});
test('bundle validation rejects missing/overlapping timing and collapsed prerequisite deadlock',()=>{const original=loadScenario();for(const edit of [p=>p.releaseBundles[0].events.push('MISSING'),p=>p.releaseBundles.push({...p.releaseBundles[0],id:'second'}),p=>p.events.find(e=>e.id==='E09').minute=99,p=>{p.events.find(e=>e.id==='E09').prerequisites=['E03'];p.events.find(e=>e.id==='E03').prerequisites=['E02'];}]){const p=structuredClone(original);edit(p);assert.throws(()=>validateScenario(p),{status:400});}});
test('failed external prerequisite or stale revision writes no partial bundle',async t=>{const f=await fixture(t);f.scenario.events.find(e=>e.id==='E10').prerequisites=['E02','E01'];await assert.rejects(f.release('E02'),{status:409});assert.equal(f.store.all('SELECT * FROM event_runs').length,0);await f.release('E01');await assert.rejects(mutateITSM({store:f.store,scenario:f.scenario,wid:f.wid,user:f.trainer,revision:0,input:{action:'release',eventId:'E02'}}),{status:409});assert.equal(f.store.all('SELECT * FROM event_runs').length,1);});
test('legacy snapshot has no implicit bundle or learning mutations; active capability changes rejected',async t=>{const f=await fixture(t,true);await f.release('E02');assert.equal((await f.read('R2')).records.length,1);assert.equal((await f.read('R5')).learning.enabled,false);await assert.rejects(f.learn('R5','draft',content),{status:409});const updated={...f.scenario,learningModel:1};await assert.rejects(saveWorkshopScenario(f.store,f.scenario,f.wid,{revision:1,pack:updated}),{status:409});});
test('knowledge needs real evidence and each foreign role action is denied',async t=>{const f=await fixture(t);await assert.rejects(f.learn('R5','draft',{...content,eventId:'E01',evidenceId:'fake'}),{status:409});for(const role of ['R1','R2','R3','R4','R6','R7','R8'])await assert.rejects(f.learn(role,'draft',content),{status:403});const a=await draft(f);await assert.rejects(f.learn('R5','publish',{articleId:a.id}),{status:409});await assert.rejects(f.learn('R2','reuse',{articleId:a.id}),{status:409});await assert.rejects(f.learn('R8','review',{articleId:a.id,option:'approve',note:'Yetkili inceleme fakat gönderilmiş sürüm değil.'}),{status:409});});
test('rejected draft can be corrected, review bound to content, identity prevents role-switch self-review',async t=>{const f=await fixture(t);const a=await draft(f);await f.learn('R5','submit',{articleId:a.id});await assert.rejects(f.learn('R5','edit',{articleId:a.id,...content,eventId:'E01',evidenceId:a.source.id}),{status:409});f.store.run('UPDATE memberships SET role_id=? WHERE workshop_id=? AND user_id=?','R8',f.wid,f.users.R5.id);await assert.rejects(f.learn('R5','review',{articleId:a.id,option:'approve',note:'Yazar rolünü değiştirerek kendi metnini onaylayamaz.'}),{status:403});f.store.run('UPDATE memberships SET role_id=? WHERE workshop_id=? AND user_id=?','R5',f.wid,f.users.R5.id);await f.learn('R8','review',{articleId:a.id,option:'reject',note:'Sınır kontrolü eksik; gerçek ziyaretçi gözlemi açıkça belirtilmeli.'});await f.learn('R5','edit',{articleId:a.id,...content,eventId:'E01',evidenceId:a.source.id});assert.equal((await f.read('R5')).learning.articles[0].review,undefined);await publish(f,a);await assert.rejects(f.learn('R5','edit',{articleId:a.id,...content}),{status:409});assert.ok((await f.read('R8')).learning.history.some(h=>h.note?.includes('Sınır kontrolü eksik')));});
test('cross-role reuse records observation, new version retires old without rewriting historical reuse',async t=>{const f=await fixture(t),a=await draft(f);await publish(f,a);await f.release('E03');const evidenceId=await f.note('R3','E03');await assert.rejects(f.learn('R2','reuse',{articleId:a.id,eventId:'E03',evidenceId,option:'worked',note:'Başkasının gözlemini kendi gözlemim diye gönderemem.'}),{status:403});await f.learn('R3','reuse',{articleId:a.id,eventId:'E03',evidenceId,option:'not_applicable',note:'Çit olayı farklı koşulda; turnike prosedürü uygun değil, saha prosedürüne dönüldü.'});const old=structuredClone((await f.read('R3')).learning.reuses);await f.learn('R5','revise',{articleId:a.id,...content,title:'Güncel turnike kapsamı ve kontrolü',eventId:'E01',evidenceId:a.source.id});const b=(await f.read('R5')).learning.articles.at(-1);assert.equal(b.version,2);assert.equal((await f.read('R2')).learning.articles[0].status,'published');await publish(f,b);let v=(await f.read('R2')).learning;assert.equal(v.articles[0].status,'retired');assert.deepEqual(v.reuses,old);await assert.rejects(f.learn('R2','reuse',{articleId:a.id,eventId:'E03',evidenceId,option:'worked',note:'Emekli sürüm yeni kullanım için geçerli olamaz.'}),{status:409});await f.learn('R5','retire',{articleId:b.id,note:'Yeni saha kanıtı bekleniyor; bu sürümle yeni uygulama yapılmamalı.'});assert.equal((await f.read('R2')).learning.metrics.published,0);assert.deepEqual((await f.read('R2')).learning.reuses,old);});
test('learning CAS and idempotency reject altered or stale writes',async t=>{const f=await fixture(t),a=await draft(f),v=await f.read('R5');const input={action:'learning',operation:'submit',articleId:a.id,runtimeRevision:v.encounter.revision,requestId:'learning-submit-once'};await f.act('R5',input);await f.act('R5',input);await assert.rejects(f.act('R5',{...input,articleId:'other'}),{status:409});await assert.rejects(f.act('R8',{...input,operation:'review',requestId:'learning-stale-review',option:'approve',note:'Eski ekran sürümü yeni kararı ezmemeli.'}),{status:409});assert.equal((await f.read('R5')).learning.history.filter(h=>h.operation==='submit').length,1);});
test('measurement and transfer are evidence not automatic mastery or ticket closure',async t=>{const f=await fixture(t);await f.release('E01');const before=(await f.read('R2')).metrics;await assert.rejects(f.learn('R4','measure',{eventId:'E01'}),{status:403});await f.learn('R8','measure',{eventId:'E01',option:'baseline',metric:'Gerçek SLA dakikası ve ilk müdahale; kaynak atölye kaydı.',note:'Başlangıçta bir açık olay var; müşteri teyidi henüz gözlenmedi.'});await f.learn('R2','transfer',{dependency:'İki sunucu aynı DNS’e bağlı; müşteri sipariş hizmeti etkilenir.',decision:'Teknik ekip planlar, hizmet sahibi kaynak ayırır, değişiklik yetkilisi onaylar.',verification:'Gerçek sipariş uçtan uca doğrulanır ve müşteri teyidi alınır.'});let l=(await f.read('R8')).learning;assert.equal(l.metrics.transferAssessed,0);await f.learn('trainer','assess',{transferId:l.transfers[0].id,dependency:'demonstrated',decision:'needs_practice',verification:'demonstrated',note:'Ortak DNS ve sipariş testi açıklanmış; acil kararın yetki sınırı tekrar çalışılmalı.'});assert.deepEqual((await f.read('R2')).metrics,before);assert.equal((await f.read('R2')).learning.metrics.transferAssessed,1);});
test('new knowledge/final acceptance gates do not claim completion from closure alone',async t=>{const f=await fixture(t);for(const eid of ['E01','E08','E12'])await f.release(eid);for(const eid of ['E08','E12']){await f.act('trainer',{action:'ack',recordId:f.wid+'__'+eid});const choice=f.scenario.events.find(e=>e.id===eid).choices.find(c=>c.resolve);await assert.rejects(f.act('trainer',{action:'evaluate',recordId:f.wid+'__'+eid,choiceId:choice.id,note:'Kanıt eksikken sadece eğitmen kapanış isteği yeterli değil.'}),{status:409});}});
test('learning UI escapes content, preserves rendered revision and separates historical score',async t=>{const f=await fixture(t),a=await draft(f);const itsm=await f.read('R5'),s={user:f.users.R5,roleId:'R5',itsm};itsm.learning.articles[0].title='<script>bad</script>';const html=learningPage(s);assert.doesNotMatch(html,/<script>/);assert.match(html,/&lt;script&gt;/);assert.match(html,/henüz yok|henüz gözlenmedi/i);assert.match(learningForm(s,'edit',a.id),new RegExp(`name="runtimeRevision" value="${itsm.encounter.revision}"`));assert.equal(itsm.encounter.learning,undefined);});
